"""
hsx_boron_inputs.py

Input handling for the standalone HSX boron 1D transport model.

The model intentionally separates:
  measured inputs:
    - electron temperature and density from HSX Thomson scattering, shot 37
      (including measurement uncertainties stored in the .mat file)
    - boron OpenADAS ADF11 ionization/recombination files

  assumed/scanned inputs:
    - ion temperature  (flat profile; no CHERS data processed yet)
    - anomalous diffusivity  (generic low/medium/high cases)
    - pinch / convective velocity  (assumed shape; not from Er measurement)
    - neutral boron source width and rate  (order-of-magnitude placeholder)

  future predictive inputs:
    - boron-specific neoclassical transport from SFINCS/PENTA
    - processed CHERS Ti(r), flow, and Er(r)
    - experimental boron line emission used to fit anomalous diffusivity

This file does not require hsxdata.hdf5 and does not claim that any C6+
transport file is boron transport.  A future boron transport CSV can be loaded
if it is generated by SFINCS/PENTA or by a validated fitting workflow.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import numpy as np
from scipy.io import loadmat
from scipy.interpolate import PchipInterpolator, RegularGridInterpolator


@dataclass
class HSXProfiles:
    rho: np.ndarray
    r_m: np.ndarray
    Te_eV: np.ndarray
    ne_m3: np.ndarray
    Ti_eV: np.ndarray
    Te_source: str
    ne_source: str
    Ti_source: str
    minor_radius_m: float
    major_radius_m: float
    # Thomson raw data and uncertainties — loaded for error-band plots.
    # These are None if the .mat file does not contain uncertainty fields.
    rho_ts: np.ndarray | None = field(default=None, repr=False)
    Te_ts: np.ndarray | None = field(default=None, repr=False)
    ne_ts: np.ndarray | None = field(default=None, repr=False)
    Te_ts_err_hi: np.ndarray | None = field(default=None, repr=False)
    Te_ts_err_lo: np.ndarray | None = field(default=None, repr=False)
    ne_ts_err_hi: np.ndarray | None = field(default=None, repr=False)
    ne_ts_err_lo: np.ndarray | None = field(default=None, repr=False)


@dataclass
class TransportInputs:
    rho: np.ndarray
    D_by_Z_m2_s: np.ndarray
    V_by_Z_m_s: np.ndarray
    D_case: str
    pinch_case: str
    source: str
    is_boron_specific: bool


def _load_vmec_radii(data_dir: Path) -> tuple[float, float, str]:
    """
    Try to get radii from the HSX VMEC file using pySTRAHL if it is installed.
    Fall back to nominal HSX radii if this helper is not available.
    """
    wout = data_dir / "wout_HSX_qhsExtend.nc"
    try:
        from pystrahl.get_rmin_rmaj_from_vmec import get_rmin_rmaj_from_vmec
        rminor_cm, rmajor_cm, _ = get_rmin_rmaj_from_vmec(str(wout), extended_vmec_factor=1.5)
        return float(rminor_cm) / 100.0, float(rmajor_cm) / 100.0, "wout_HSX_qhsExtend.nc via pySTRAHL VMEC helper"
    except Exception:
        return 0.12, 1.20, "nominal HSX radii: a=0.12 m, R=1.20 m"


def load_profiles(
    data_dir: str | Path,
    n_points: int = 180,
    ti_case_eV: float = 70.0,
    edge_Te_eV: float = 40.0,
    edge_ne_m3: float = 1.0e18,
) -> HSXProfiles:
    """
    Load measured shot-37 Thomson Te/ne, including uncertainty bands,
    and extend to the LCFS with explicit assumed edge anchors.

    Thomson coverage for shot 37: rho = 0.016 to 0.906 (10 chords).
    The inner anchor (rho=0) is set equal to the innermost chord value
    (rho=0.016, Te~982 eV) — this is nearly on-axis and introduces
    negligible error.
    The outer anchor (rho=1.0) uses edge_Te_eV and edge_ne_m3, which are
    ORDER-OF-MAGNITUDE ESTIMATES for the HSX scrape-off layer.  They are
    NOT measurements from shot 37 and must be clearly labeled as assumptions.
    Typical HSX SOL values (~30-60 eV, ~5e17-2e18 m^-3) bracket the defaults.

    Interpolation: PCHIP (monotone-preserving cubic Hermite) with explicit
    anchors at rho=0 and rho=1.  extrapolate=False is set; any rho outside
    [0,1] would raise rather than silently extrapolate.
    """
    data_dir = Path(data_dir)
    a_m, R_m, radius_source = _load_vmec_radii(data_dir)

    rho = np.linspace(0.0, 1.0, n_points)
    r_m = rho * a_m

    ts_path = data_dir / "2026-04-15_shot37_t0p83-0p85.mat"
    if not ts_path.exists():
        raise FileNotFoundError(f"Missing Thomson file: {ts_path}")

    mat = loadmat(ts_path)
    rho_ts = np.asarray(mat["roa"], dtype=float).ravel()
    Te_ts  = np.asarray(mat["Te"],  dtype=float).ravel()
    ne_ts  = np.asarray(mat["ne"],  dtype=float).ravel()

    # Load uncertainty arrays if present in the .mat file.
    def _safe(key):
        return np.asarray(mat[key], dtype=float).ravel() if key in mat else None

    Te_err_hi_raw = _safe("Te_std_high")
    Te_err_lo_raw = _safe("Te_std_low")
    ne_err_hi_raw = _safe("ne_std_high")
    ne_err_lo_raw = _safe("ne_std_low")

    good = np.isfinite(rho_ts) & np.isfinite(Te_ts) & np.isfinite(ne_ts)
    order = np.argsort(rho_ts[good])

    def _apply(arr):
        if arr is None:
            return None
        return arr[good][order]

    rho_ts = rho_ts[good][order]
    Te_ts  = Te_ts[good][order]
    ne_ts  = ne_ts[good][order]
    Te_err_hi = _apply(Te_err_hi_raw)
    Te_err_lo = _apply(Te_err_lo_raw)
    ne_err_hi = _apply(ne_err_hi_raw)
    ne_err_lo = _apply(ne_err_lo_raw)

    # Add axis and edge anchors.
    # Axis: pinned to innermost chord (rho=0.016 ~ 0, near-axis measurement).
    # LCFS: ASSUMED edge condition — not a measurement.
    rho_ext = np.concatenate(([0.0], rho_ts, [1.0]))
    Te_ext  = np.concatenate(([Te_ts[0]], Te_ts, [edge_Te_eV]))
    ne_ext  = np.concatenate(([ne_ts[0]], ne_ts, [edge_ne_m3]))

    Te_interp = PchipInterpolator(rho_ext, Te_ext, extrapolate=False)
    ne_interp = PchipInterpolator(rho_ext, ne_ext, extrapolate=False)

    Te_eV = np.maximum(Te_interp(rho), 1.0)
    ne_m3 = np.maximum(ne_interp(rho), 1e15)
    Ti_eV = np.full_like(rho, float(ti_case_eV))

    return HSXProfiles(
        rho=rho,
        r_m=r_m,
        Te_eV=Te_eV,
        ne_m3=ne_m3,
        Ti_eV=Ti_eV,
        Te_source=f"Thomson shot 37 (rho=0.016-0.906) + assumed LCFS Te={edge_Te_eV:g} eV",
        ne_source=f"Thomson shot 37 (rho=0.016-0.906) + assumed LCFS ne={edge_ne_m3:.2e} m^-3",
        Ti_source=f"ASSUMED constant Ti={ti_case_eV:g} eV — not measured; replace with CHERS Ti(r)",
        minor_radius_m=a_m,
        major_radius_m=R_m,
        rho_ts=rho_ts,
        Te_ts=Te_ts,
        ne_ts=ne_ts,
        Te_ts_err_hi=Te_err_hi,
        Te_ts_err_lo=Te_err_lo,
        ne_ts_err_hi=ne_err_hi,
        ne_ts_err_lo=ne_err_lo,
    )


def _read_adf11_unresolved(path: Path):
    """
    Minimal ADF11 unresolved reader for OpenADAS SCD/ACD files.

    OpenADAS ADF11 stores:
      - log10 density grid [cm^-3]
      - log10 temperature grid [eV]
      - log10 rate coefficients [cm^3/s]

    The returned arrays are in log10 space; unit conversion to s^-1 is done
    by the caller after multiplying by ne in cm^-3.

    VALIDATION NOTE:
      This reader has been validated against scd89_b.dat and acd89_b.dat only.
      The parser locates data blocks by seeking the first run of numeric tokens,
      which is fragile for ADF11 files that have numeric content in header
      comments.  For future files, prefer the official OpenADAS Python client
      (openadas.read_adf11) or verify the parsed grids manually.

    BORON-SPECIFIC ASSERTION:
      nion is asserted to equal 5 (the number of ionisation stages for boron,
      Z=1 through Z=5).  This prevents silently proceeding with wrong atomic
      physics if a non-boron ADF11 file is accidentally placed in DATA/.
    """
    lines = path.read_text(errors="ignore").splitlines()
    first = lines[0].split()
    nion, nne, nT = int(first[0]), int(first[1]), int(first[2])

    # --- Boron-specific safety check ---
    if nion != 5:
        raise ValueError(
            f"ADF11 file '{path.name}': expected nion=5 (boron has 5 ionisation "
            f"stages), got nion={nion}.  Ensure you are using a boron ADF11 file "
            f"(scd89_b.dat / acd89_b.dat).  A carbon file (nion=6) is a common "
            f"mistake."
        )

    def vals(line):
        out = []
        for tok in line.replace("D", "E").split():
            try:
                out.append(float(tok))
            except ValueError:
                pass
        return out

    i = 1
    while i < len(lines) and not vals(lines[i]):
        i += 1

    dens = []
    while len(dens) < nne:
        dens.extend(vals(lines[i]))
        i += 1

    temp = []
    while len(temp) < nT:
        temp.extend(vals(lines[i]))
        i += 1

    blocks = np.zeros((nion, nT, nne))
    for z in range(nion):
        while i < len(lines) and not vals(lines[i]):
            i += 1
        dat = []
        while i < len(lines) and len(dat) < nne * nT:
            dat.extend(vals(lines[i]))
            i += 1
        if len(dat) < nne * nT:
            raise ValueError(f"ADF11 file ended early: {path}")
        blocks[z] = np.asarray(dat[:nne * nT]).reshape(nT, nne)

    return np.asarray(dens[:nne]), np.asarray(temp[:nT]), blocks


def _interp_adf11_rate_file(adf11_path: Path, Te_eV: np.ndarray, ne_m3: np.ndarray) -> np.ndarray:
    """
    Interpolate an ADF11 rate file and return rates in s^-1.

    Unit conversion:
        ne_m3 / 1e6   =>  ne_cm3  [cm^-3]   (1 m^-3 = 1e-6 cm^-3)
        coeff [cm^3/s] * ne_cm3 [cm^-3]  =>  rate [s^-1]

    Interpolation is in log10(Te) and log10(ne) space.  Input values are
    clipped to the ADAS grid bounds so no extrapolation occurs.
    """
    log_ne_grid, log_Te_grid, log_coeff = _read_adf11_unresolved(adf11_path)

    ne_cm3 = np.maximum(ne_m3 / 1e6, 1.0)
    Te_eV  = np.maximum(Te_eV, 1.0)

    pts = np.column_stack([
        np.clip(np.log10(Te_eV),  log_Te_grid[0], log_Te_grid[-1]),
        np.clip(np.log10(ne_cm3), log_ne_grid[0], log_ne_grid[-1]),
    ])

    out = np.zeros((len(Te_eV), log_coeff.shape[0]))
    for z in range(log_coeff.shape[0]):
        interp = RegularGridInterpolator(
            (log_Te_grid, log_ne_grid),
            log_coeff[z],
            bounds_error=False,
            fill_value=None,
        )
        coeff_cm3_s = 10.0 ** interp(pts)
        out[:, z] = coeff_cm3_s * ne_cm3
    return out


def load_boron_adas_rates(profiles: HSXProfiles, data_dir: str | Path):
    """
    Load boron OpenADAS SCD/ACD files from DATA/.

    Required files:
        DATA/scd89_b.dat   — electron-impact ionisation coefficients
        DATA/acd89_b.dat   — radiative + dielectronic recombination coefficients

    NOTE: charge-exchange recombination (which depends on Ti and requires
    CX cross-sections) is NOT included.  This is acceptable for first-pass
    modeling but becomes important when Ti is large or when there is a
    significant neutral hydrogen population.

    Returns:
        ionization_s    : shape (nr, 5)  — rates [s^-1] for B0->B1 ... B4->B5
        recombination_s : shape (nr, 5)  — rates [s^-1] for B1->B0 ... B5->B4
        metadata        : dict
    """
    data_dir = Path(data_dir)
    scd_path = data_dir / "scd89_b.dat"
    acd_path = data_dir / "acd89_b.dat"

    if not scd_path.exists() or not acd_path.exists():
        raise FileNotFoundError(
            "Missing boron ADF11 files. Put scd89_b.dat and acd89_b.dat in DATA/."
        )

    ionization_s    = _interp_adf11_rate_file(scd_path, profiles.Te_eV, profiles.ne_m3)
    recombination_s = _interp_adf11_rate_file(acd_path, profiles.Te_eV, profiles.ne_m3)

    return ionization_s[:, :5], recombination_s[:, :5], {
        "source": "local OpenADAS ADF11",
        "scd_file": str(scd_path.name),
        "acd_file": str(acd_path.name),
        "cx_recombination_included": False,
    }


def generic_diffusivity_profile(rho: np.ndarray, case: str) -> np.ndarray:
    """
    Generic anomalous diffusivity profiles for sensitivity studies.

    These are NOT fitted to boron data.  They are deliberately simple
    parabolic profiles in rho^2 used to span a plausible HSX anomalous
    transport range, roughly consistent with turbulence estimates for
    comparable helical devices:
        low    : D_core=0.01, D_edge=0.05  m^2/s  (near-neoclassical)
        medium : D_core=0.05, D_edge=0.40  m^2/s  (moderate anomalous)
        high   : D_core=0.15, D_edge=1.00  m^2/s  (strong anomalous)

    None of these cases should be presented as the correct answer.  They are
    inputs to a sensitivity scan.
    """
    rho = np.asarray(rho, dtype=float)
    case = case.lower()

    if case == "low":
        D_core, D_edge = 0.01, 0.05
    elif case == "medium":
        D_core, D_edge = 0.05, 0.40
    elif case == "high":
        D_core, D_edge = 0.15, 1.00
    else:
        raise ValueError("D case must be 'low', 'medium', or 'high'.")

    return D_core + (D_edge - D_core) * rho**2


def generic_pinch_profile(rho: np.ndarray, charge_state: int, case: str) -> np.ndarray:
    """
    Assumed convective velocity profile.

    This is NOT a self-consistent Er calculation.  It is an ad hoc profile
    included only to test how an inward pinch term changes the result.

    Shape: sin(pi*rho)^1.5 * (0.4 + 0.6*rho) — a smooth bell-like function
    that peaks in the outer half and vanishes at the axis and edge.  This
    shape has no direct physical derivation; it is chosen to be smooth and
    physically plausible (no pinch at the axis or beyond the LCFS).

    Amplitude convention (charge_scaled case):
        amplitude = -0.08 * charge_state / 5.0   [m/s]

    The denominator 5 normalizes by Z_max for boron (B5+, fully stripped),
    so that B5+ receives the full amplitude of -0.08 m/s and lower charge
    states receive proportionally smaller pinch.  This is NOT the same as
    the Z/6 scaling sometimes used for C6+ analogy (where the denominator
    would be 6 and B5+ would receive 5/6 of the amplitude).  The choice of
    denominator 5 simply makes B5+ the reference state.  Neither the
    amplitude (-0.08 m/s) nor the shape is derived from a neoclassical or
    experimental Er profile; both are assumed.

    For charge_state == 0 (neutral boron) or case == 'off', the pinch is
    always zero.
    """
    rho = np.asarray(rho, dtype=float)
    case = case.lower()

    if charge_state == 0 or case == "off":
        return np.zeros_like(rho)

    # Smooth bell shape: peaks in outer half, zero at axis and edge.
    shape = np.sin(np.pi * rho) ** 1.5
    shape *= (0.4 + 0.6 * rho)

    if case == "assumed_inward":
        # Charge-independent amplitude; same pinch for all ion states.
        amplitude = -0.08
    elif case == "charge_scaled":
        # Scale linearly with charge state, normalized to B5+ (Z_max = 5).
        # B1+: -0.016 m/s; B5+: -0.08 m/s.  See docstring for caveats.
        amplitude = -0.08 * (charge_state / 5.0)
    else:
        raise ValueError("Pinch case must be 'off', 'assumed_inward', or 'charge_scaled'.")

    return amplitude * shape


def load_future_boron_transport_csv(path: str | Path, rho_target: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Optional loader for future boron-specific transport coefficients.

    Expected CSV header:
        rho,D_B1,V_B1,D_B2,V_B2,D_B3,V_B3,D_B4,V_B4,D_B5,V_B5

    D_B0 and V_B0 are set to D_B1 and 0 respectively (neutral boron
    diffuses at the same rate as B1+; no pinch for neutrals).

    This function is only called when --future-boron-transport-csv is
    supplied on the command line.  Only then should transport be described
    as boron-specific.
    """
    path = Path(path)
    data = np.genfromtxt(path, delimiter=",", names=True)

    rho_data = data["rho"]
    nr = len(rho_target)
    D_by_Z = np.zeros((6, nr))
    V_by_Z = np.zeros((6, nr))

    # Neutral boron: use B1 diffusivity as a simple placeholder; no pinch.
    D_by_Z[0] = np.interp(rho_target, rho_data, data["D_B1"])
    V_by_Z[0] = 0.0

    for Z in range(1, 6):
        D_by_Z[Z] = np.interp(rho_target, rho_data, data[f"D_B{Z}"])
        V_by_Z[Z] = np.interp(rho_target, rho_data, data[f"V_B{Z}"])

    return D_by_Z, V_by_Z


def build_transport_arrays(
    rho: np.ndarray,
    D_case: str = "medium",
    pinch_case: str = "charge_scaled",
    future_boron_transport_csv: str | Path | None = None,
) -> TransportInputs:
    """
    Build D and V arrays for the transport solver.

    If future_boron_transport_csv is supplied, the model uses those values
    and marks the transport as boron-specific.  Otherwise it uses generic
    sensitivity-study profiles and clearly marks them as assumed.
    """
    rho = np.asarray(rho, dtype=float)

    if future_boron_transport_csv is not None:
        D_by_Z, V_by_Z = load_future_boron_transport_csv(future_boron_transport_csv, rho)
        return TransportInputs(
            rho=rho,
            D_by_Z_m2_s=D_by_Z,
            V_by_Z_m_s=V_by_Z,
            D_case="future_csv",
            pinch_case="future_csv",
            source=str(future_boron_transport_csv),
            is_boron_specific=True,
        )

    D_base = generic_diffusivity_profile(rho, D_case)
    # Same D for all charge states in the generic case.
    D_by_Z = np.repeat(D_base[None, :], 6, axis=0)

    V_by_Z = np.zeros((6, len(rho)))
    for Z in range(6):
        V_by_Z[Z] = generic_pinch_profile(rho, Z, pinch_case)

    return TransportInputs(
        rho=rho,
        D_by_Z_m2_s=D_by_Z,
        V_by_Z_m_s=V_by_Z,
        D_case=D_case,
        pinch_case=pinch_case,
        source="generic assumed/scanned transport",
        is_boron_specific=False,
    )
